### ISSUE TITLE
FSLeyes and AxonDeepSeg have incompatible numpy versions

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#174]
FSLeyes requires numpy 1.16.2 while AxonDeepSeg requires numpy 1.14.5

If I try to use the line `from AxonDeepSeg.apply_model import axon_segmentation`
on a python console with numpy 1.16.2 installed, I get the following error:

~~~
Traceback (most recent call last):
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a71bb435a888>", line 1, in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
  File "/Users/stoyan_admin/Desktop/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/axondeepseg/AxonDeepSeg/apply_model.py", line 4, in <module>
    from skimage.transform import rescale, resize
  File "/Users/stoyan_admin/Desktop/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/Users/stoyan_admin/Desktop/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/util/__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "/Users/stoyan_admin/Desktop/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
~~~

On the other hand, if I try to open FSLeyes with numpy 1.14.5, I get the following message and FSLeyes doesn't launch

~~~
(venv) coltrane:~/PycharmProjects/FSLeyes_testing4/venv $ fsleyes
/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/__init__.py:268: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'MacOSX' by the following code:
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/bin/fsleyes", line 11, in <module>
    sys.exit(main())
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/main.py", line 202, in main
    fsleyes.initialise()
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/__init__.py", line 263, in initialise
    plugins.initialise()
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/plugins.py", line 197, in initialise
    loadPlugin(fname)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/plugins.py", line 349, in loadPlugin
    entryPoints = _findEntryPoints(filename, modname)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/plugins.py", line 300, in _findEntryPoints
    spec.loader.exec_module(mod)
  File "/Users/stoyan_admin/.fsleyes/plugins/ads_plugin_v2.py", line 11, in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/axondeepseg/AxonDeepSeg/apply_model.py", line 10, in <module>
    from .visualization.get_masks import get_masks
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/axondeepseg/AxonDeepSeg/visualization/get_masks.py", line 3, in <module>
    from skimage import io
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 93, in reset_plugins
    _load_preferred_plugins()
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 73, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 85, in _set_plugin
    use_plugin(plugin, kind=plugin_type)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 255, in use_plugin
    _load(name)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 299, in _load
    fromlist=[modname])
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/skimage/io/_plugins/matplotlib_plugin.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  mpl.use('WxAgg')

~~~
I tried with numpy 1.15 and it doesn't work either.

**Comment by Stoyan-I-A** [comment]
What I need is to run a prediction model on an existing PNG image. Is there a way to write a method that would execute a script in another python environment?

**Comment by jcohenadad** [comment]
@Stoyan-I-A looks like your import error with numpy 1.16.2 is caused by skimage-- have you tried to satisfy numpy's dependencies by upgrading other module (skimage, etc.)?

**Comment by Stoyan-I-A** [comment]
@jcohenadad I upgraded scikit-image to version 0.14.2 and it doesn't show the error anymore.
Thank you.

**Comment by jcohenadad** [comment]
great, make sure to update the requirements.txt file in your branch otherwise this issue will appear again in production mode
