### ISSUE TITLE
FSLeyes integration - investigate the bug with large images that are not properly displayed

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#209]

**Comment by Stoyan-I-A** [comment]
Update :
I tried to load screenshots of different sizes into FSLeyes. The screenshots were taken using the same method (cmd+shift+4 on a mac). I used screenshots because they are easy to take.

I was able to load a screenshot with a size of 1927 x 1273 pixels. No problem here.

Then, I tried loading a screenshot with a size of 2560 x 1440 pixels. The image wasn't displayed. The overlay was loaded but nothing is displayed on the canvas. Yet, the cursor shows the intensity of the pixels in the location panel.
The following message also appeared in the console:
```
Traceback (most recent call last):
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsl/utils/idle.py", line 339, in _wxIdleLoop
    task.task(*task.args, **task.kwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes_widgets/utils/status.py", line 178, in wrapper
    func(*wargs, **wkwargs)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/fsleyes/gl/textures/texture3d.py", line 808, in configTexture
    None)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6561)
  File "wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6439)
  File "/Users/stoyan_admin/PycharmProjects/FSLeyes_testing4/venv/lib/python3.6/site-packages/OpenGL/logs.py", line 67, in __call__
    return function( *args, **named )
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glTexImage3D,
	pyArgs = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		2560,
		1440,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		2560,
		1440,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_3D,
		0,
		GL_R8,
		2560,
		1440,
		1,
		0,
		GL_RED,
		GL_UNSIGNED_BYTE,
		None,
	)
)
```
I also went in debug mode, I couldn't find anything in my script that causes this error, so I believe it is a bug from FSLeyes. 
I will contact the FSLeyes developers about this.

**Comment by Stoyan-I-A** [comment]
I wrote an issue on the FSLeyes GitHub page :
https://github.com/pauldmccarthy/fsleyes/issues/23

**Comment by Stoyan-I-A** [comment]
The developer responded. I suggest you to read his answer : https://github.com/pauldmccarthy/fsleyes/issues/23 , but the conclusion is that we will have to work around it. This might require a discussion in a future meeting.

**Comment by mathieuboudreau** [comment]
That's disappointing; I don't think we want to downsample the images, as we want to use the visualised image to draw masks, which needs pixel-precision.

**Comment by jcohenadad** [comment]
hum... i don't have any satisfactory workaround on top of my head :-(

**Comment by Stoyan-I-A** [comment]
2D support was added to FSLeyes. However, the software seems to have issues when loading certain images. I tried to load a few images but an error poped up on most of them.
More info on https://github.com/pauldmccarthy/fsleyes/issues/23
