### ISSUE TITLE
Unable to segment a large TEM image

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#230]
![image](https://user-images.githubusercontent.com/43790661/60543093-4a933900-9cca-11e9-8164-b0aa3ad43fd7.png)
[pixel_size_in_micrometer.txt](https://github.com/neuropoly/axondeepseg/files/3352128/pixel_size_in_micrometer.txt)

This image can be found in [OSF](https://osf.io/rtbwc/) under `test_segmentation/test_tem_image/image1_tem/image.png `

I tried to segment it after installing the master branch of axondeepseg by using the command `axondeepseg -t TEM -i image.png`

This is the output :
```
Using TensorFlow backend.
AxonDeepSeg v.2.2dev
2019-07-02 13:02:30.795706: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-07-02 13:02:30.795753: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-07-02 13:02:30.795762: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-07-02 13:02:30.795767: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-07-02 13:02:30.795771: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [5,5,3,16] rhs shape= [5,5,1,16]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@cconv-d0-c0/convolution/conv2d_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](cconv-d0-c0/convolution/conv2d_1/kernel, save/RestoreV2_8)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stoyan/miniconda/envs/ads_venv/bin/axondeepseg", line 11, in <module>
    load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg')()
  File "/home/stoyan/axondeepseg/AxonDeepSeg/segment.py", line 385, in main
    verbosity_level=verbosity_level)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/apply_model.py", line 277, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/apply_model.py", line 95, in apply_convnet
    saver.restore(sess, str(model_previous_path))
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [5,5,3,16] rhs shape= [5,5,1,16]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@cconv-d0-c0/convolution/conv2d_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](cconv-d0-c0/convolution/conv2d_1/kernel, save/RestoreV2_8)]]

Caused by op 'save/Assign_8', defined at:
  File "/home/stoyan/miniconda/envs/ads_venv/bin/axondeepseg", line 11, in <module>
    load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg')()
  File "/home/stoyan/axondeepseg/AxonDeepSeg/segment.py", line 385, in main
    verbosity_level=verbosity_level)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/segment.py", line 94, in segment_image
    prediction_proba_activate=False, write_mode=True)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/apply_model.py", line 277, in axon_segmentation
    verbosity_level=verbosity_level)
  File "/home/stoyan/axondeepseg/AxonDeepSeg/apply_model.py", line 83, in apply_convnet
    saver = tf.train.Saver()  # Load previous model
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/stoyan/miniconda/envs/ads_venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [5,5,3,16] rhs shape= [5,5,1,16]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@cconv-d0-c0/convolution/conv2d_1/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](cconv-d0-c0/convolution/conv2d_1/kernel, save/RestoreV2_8)]]

swig/python detected a memory leak of type 'int64_t *', no destructor found.
```

**Comment by vs74** [comment]
@Stoyan-I-A, I will look into it.

**Comment by vs74** [comment]
@Stoyan-I-A, I have fixed the issue. You can for now use the branch [dev_issue230](https://github.com/neuropoly/axondeepseg/tree/dev_issue230) until it's merged to master.

**Comment by Stoyan-I-A** [comment]
Nice job! The output image looks good.
![image_seg-axonmyelin](https://user-images.githubusercontent.com/43790661/60559947-03756a00-9d03-11e9-81b5-ca83e4b703fd.png)

**Comment by jcohenadad** [comment]
issues should only be closed when PR is merged.
this is done automatically
