### ISSUE TITLE
inst: virtualenv from miniconda2 seems to crash

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#25]
~~~
virtualenv ads_venv
Overwriting /Users/julien/ads_venv/lib/python2.7/orig-prefix.txt with new content
New python executable in /Users/julien/ads_venv/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/julien/ads_venv/bin/python - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/julien/ads_venv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/julien/ads_venv/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/julien/ads_venv/lib/python2.7/lib-dynload/_io.so
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/julien/ads_venv/bin/python - setuptools pip wheel failed with error code 1
~~~

**Comment by jcohenadad** [comment]
never close an issue without referencing to the commit that fixes the issue.

**Comment by jcohenadad** [comment]
now fixed
