### ISSUE TITLE
AxonDeepSeg fails to install on Windows 10

### ISSUE THREAD

**Issue by Stoyan-I-A** [neuropoly/axondeepseg#361]
It seems to be related to the model download.
Check details for the full command prompt log.

More info:
- The `default_TEM_model` was downloaded, but it wasn't moved to axondeepseg/models
- If I comment out the command that downloads the models in `setup.py` the rest of the software successfully installs

<details>

~~~

(ADS_project2) C:\Users\Stoyan\PycharmProjects\ADS_project2\axondeepseg>pip install -e .
Obtaining file:///C:/Users/Stoyan/PycharmProjects/ADS_project2/axondeepseg
Collecting numpy==1.16.4
  Using cached numpy-1.16.4-cp37-cp37m-win_amd64.whl (11.9 MB)
Collecting scipy==1.3.0
  Using cached scipy-1.3.0-cp37-cp37m-win_amd64.whl (30.3 MB)
Collecting scikit-learn==0.19.2
  Using cached scikit_learn-0.19.2-cp37-cp37m-win_amd64.whl (4.4 MB)
Collecting scikit-image==0.14.2
  Using cached scikit_image-0.14.2-cp37-none-win_amd64.whl (24.6 MB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\33\63\72\4156fe55e8e06830d7aed3d20a6d1aacc753536843ab7330f6\tabulate-0.8.2-py3-none-any.whl
Collecting pandas==0.23.3
  Using cached pandas-0.23.3-cp37-cp37m-win_amd64.whl (7.9 MB)
Collecting matplotlib==3.1.0
  Using cached matplotlib-3.1.0-cp37-cp37m-win_amd64.whl (9.1 MB)
Collecting tensorflow==1.13.1
  Using cached tensorflow-1.13.1-cp37-cp37m-win_amd64.whl (63.1 MB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\26\70\6a\1c79e59951a41b4045497da187b2724f5659ca64033cf4548e\mpld3-0.3-py3-none-any.whl
Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
Collecting requests==2.20.1
  Using cached requests-2.20.1-py2.py3-none-any.whl (57 kB)
Collecting pillow==6.2.0
  Using cached Pillow-6.2.0-cp37-cp37m-win_amd64.whl (2.0 MB)
Collecting imageio==2.3.0
  Using cached imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
Collecting pytest==4.6.3
  Using cached pytest-4.6.3-py2.py3-none-any.whl (229 kB)
Collecting pytest-cov==2.5.1
  Using cached pytest_cov-2.5.1-py2.py3-none-any.whl (21 kB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\8c\76\0b\eb9eb3da7e2335e3577e3f96a0ae9f74f206e26457bd1a2bc8\prettytable-0.7.2-py3-none-any.whl
Collecting raven==6.8.0
  Using cached raven-6.8.0-py2.py3-none-any.whl (285 kB)
Collecting jupyter>=1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting Keras==2.2.4
  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)
Collecting Keras-Applications==1.0.8
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting Keras-Preprocessing==1.1.0
  Using cached Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41 kB)
Collecting opencv-contrib-python==4.1.0.25
  Using cached opencv_contrib_python-4.1.0.25-cp37-cp37m-win_amd64.whl (43.7 MB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\f1\7b\dc\0a583597b903c07c818f7e570c1007d1447dc9e2bff575a73a\albumentations-0.3.0-py3-none-any.whl
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\9d\de\b7\829f0deadb395cbc720c9bac48adf7b7696f62a64537e1759a\openpyxl-2.6.3-py2.py3-none-any.whl
Collecting networkx>=1.8
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting cloudpickle>=0.2.1
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting dask[array]>=1.0.0
  Using cached dask-2.30.0-py3-none-any.whl (848 kB)
Collecting PyWavelets>=0.4.0
  Using cached PyWavelets-1.1.1-cp37-cp37m-win_amd64.whl (4.2 MB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting python-dateutil>=2.5.0
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2011k
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp37-none-win_amd64.whl (57 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting tensorboard<1.14.0,>=1.13.0
  Using cached tensorboard-1.13.1-py3-none-any.whl (3.2 MB)
Collecting protobuf>=3.6.1
  Using cached protobuf-3.13.0-cp37-cp37m-win_amd64.whl (1.0 MB)
Collecting gast>=0.2.0
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0
  Using cached tensorflow_estimator-1.13.0-py2.py3-none-any.whl (367 kB)
Requirement already satisfied: wheel>=0.26 in c:\users\stoyan\miniconda3\envs\ads_project2\lib\site-packages (from tensorflow==1.13.1->AxonDeepSeg==3.2) (0.35.1)
Collecting absl-py>=0.1.6
  Using cached absl_py-0.10.0-py3-none-any.whl (127 kB)
Collecting astor>=0.6.0
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2\termcolor-1.1.0-py3-none-any.whl
Collecting grpcio>=1.8.6
  Using cached grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting urllib3<1.25,>=1.21.1
  Using cached urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Collecting idna<2.8,>=2.5
  Using cached idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting chardet<3.1.0,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\stoyan\miniconda3\envs\ads_project2\lib\site-packages (from requests==2.20.1->AxonDeepSeg==3.2) (2020.6.20)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting importlib-metadata>=0.12
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting colorama; sys_platform == "win32"
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting more-itertools>=4.0.0; python_version > "2.7"
  Using cached more_itertools-8.5.0-py3-none-any.whl (44 kB)
Collecting py>=1.5.0
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting atomicwrites>=1.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting coverage>=3.7.1
  Using cached coverage-5.3-cp37-cp37m-win_amd64.whl (208 kB)
Collecting ipywidgets
  Using cached ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
Collecting ipykernel
  Using cached ipykernel-5.3.4-py3-none-any.whl (120 kB)
Collecting nbconvert
  Using cached nbconvert-6.0.7-py3-none-any.whl (552 kB)
Collecting jupyter-console
  Using cached jupyter_console-6.2.0-py3-none-any.whl (22 kB)
Collecting qtconsole
  Using cached qtconsole-4.7.7-py2.py3-none-any.whl (118 kB)
Collecting notebook
  Using cached notebook-6.1.4-py3-none-any.whl (9.5 MB)
Collecting h5py
  Using cached h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
Collecting pyyaml
  Using cached PyYAML-5.3.1-cp37-cp37m-win_amd64.whl (216 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.4.0.44-cp37-cp37m-win_amd64.whl (33.4 MB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\89\72\98\3ebfdba1069a9a8eaaa7ae7265cfd67d63ef0197aaee2e5f9c\imgaug-0.2.6-py3-none-any.whl
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\e2\bd\55\048b4fd505716c4c298f42ee02dffd9496bb6d212b266c7f31\et_xmlfile-1.0.1-py3-none-any.whl
Collecting jdcal
  Using cached jdcal-1.4.1-py2.py3-none-any.whl (9.5 kB)
Collecting decorator>=4.3.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting toolz>=0.8.2; extra == "array"
  Using cached toolz-0.11.1-py3-none-any.whl (55 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3-py3-none-any.whl (94 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Requirement already satisfied: setuptools in c:\users\stoyan\miniconda3\envs\ads_project2\lib\site-packages (from protobuf>=3.6.1->tensorflow==1.13.1->AxonDeepSeg==3.2) (50.3.0.post20201006)
Collecting mock>=2.0.0
  Using cached mock-4.0.2-py3-none-any.whl (28 kB)
Collecting zipp>=0.5
  Using cached zipp-3.3.0-py3-none-any.whl (5.3 kB)
Collecting nbformat>=4.2.0
  Using cached nbformat-5.0.7-py3-none-any.whl (170 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Collecting traitlets>=4.3.1
  Using cached traitlets-5.0.4-py3-none-any.whl (98 kB)
Collecting ipython>=4.0.0; python_version >= "3.3"
  Using cached ipython-7.18.1-py3-none-any.whl (786 kB)
Collecting tornado>=4.2
  Using cached tornado-6.0.4-cp37-cp37m-win_amd64.whl (417 kB)
Collecting jupyter-client
  Using cached jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting jupyterlab-pygments
  Using cached jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting jinja2>=2.4
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\63\99\01\9fe785b86d1e091a6b2a61e06ddb3d8eb1bc9acae5933d4740\pandocfilters-1.4.2-py3-none-any.whl
Collecting pygments>=2.4.1
  Using cached Pygments-2.7.1-py3-none-any.whl (944 kB)
Collecting testpath
  Using cached testpath-0.4.4-py2.py3-none-any.whl (163 kB)
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting nbclient<0.6.0,>=0.5.0
  Using cached nbclient-0.5.0-py3-none-any.whl (65 kB)
Collecting bleach
  Using cached bleach-3.2.1-py2.py3-none-any.whl (145 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting entrypoints>=0.2.2
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.7-py3-none-any.whl (355 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting qtpy
  Using cached QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
Collecting pyzmq>=17.1
  Using cached pyzmq-19.0.2-cp37-cp37m-win_amd64.whl (1.0 MB)
Collecting argon2-cffi
  Using cached argon2_cffi-20.1.0-cp37-cp37m-win_amd64.whl (42 kB)
Collecting terminado>=0.8.3
  Using cached terminado-0.9.1-py3-none-any.whl (13 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.8.0-py2.py3-none-any.whl (53 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-win_amd64.whl (16 kB)
Collecting nest-asyncio
  Using cached nest_asyncio-1.4.1-py3-none-any.whl (5.2 kB)
Collecting async-generator
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting pywin32>=1.0; sys_platform == "win32"
  Using cached pywin32-228-cp37-cp37m-win_amd64.whl (9.1 MB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.3-cp37-cp37m-win_amd64.whl (178 kB)
Collecting pywinpty>=0.5; os_name == "nt"
  Using cached pywinpty-0.5.7-cp37-cp37m-win_amd64.whl (1.3 MB)
Processing c:\users\stoyan\appdata\local\pip\cache\wheels\a5\52\bf\71258a1d7b3c8cbe1ee53f9314c6f65f20385481eaee573cc5\pyrsistent-0.17.3-cp37-cp37m-win_amd64.whl
Collecting parso<0.8.0,>=0.7.0
  Using cached parso-0.7.1-py2.py3-none-any.whl (109 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: numpy, scipy, scikit-learn, decorator, networkx, cloudpickle, pillow, pyyaml, toolz, dask, PyWavelets, six, scikit-image, tabulate, python-dateutil, pytz, pandas, pyparsing, kiwisolver, cycler, matplotlib, zipp, importlib-metadata, markd
own, werkzeug, protobuf, absl-py, grpcio, tensorboard, gast, mock, tensorflow-estimator, Keras-Preprocessing, h5py, Keras-Applications, astor, termcolor, tensorflow, mpld3, tqdm, urllib3, idna, chardet, requests, imageio, packaging, colorama, pluggy, more-itertools, p
y, attrs, wcwidth, atomicwrites, pytest, coverage, pytest-cov, prettytable, raven, ipython-genutils, traitlets, pickleshare, prompt-toolkit, parso, jedi, pygments, backcall, ipython, tornado, pywin32, jupyter-core, pyzmq, jupyter-client, ipykernel, pyrsistent, jsonsch
ema, nbformat, mistune, jupyterlab-pygments, MarkupSafe, jinja2, pandocfilters, testpath, defusedxml, nest-asyncio, async-generator, nbclient, webencodings, bleach, entrypoints, nbconvert, pycparser, cffi, argon2-cffi, pywinpty, terminado, prometheus-client, Send2Tras
h, notebook, widgetsnbextension, ipywidgets, jupyter-console, qtpy, qtconsole, jupyter, Keras, opencv-contrib-python, opencv-python-headless, imgaug, albumentations, et-xmlfile, jdcal, openpyxl, AxonDeepSeg
  Running setup.py develop for AxonDeepSeg
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Stoyan\Miniconda3\envs\ADS_project2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stoyan\\PycharmProjects\\ADS_project2\\axondeepseg\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stoyan\\PycharmProjects\\ADS_project
2\\axondeepseg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\Stoyan\PycharmProjects\ADS_project2\axondeepseg\
    Complete output (66 lines):
    running develop
    running egg_info
    creating AxonDeepSeg.egg-info
    writing AxonDeepSeg.egg-info\PKG-INFO
    writing dependency_links to AxonDeepSeg.egg-info\dependency_links.txt
    writing entry points to AxonDeepSeg.egg-info\entry_points.txt
    writing requirements to AxonDeepSeg.egg-info\requires.txt
    writing top-level names to AxonDeepSeg.egg-info\top_level.txt
    writing manifest file 'AxonDeepSeg.egg-info\SOURCES.txt'
    reading manifest file 'AxonDeepSeg.egg-info\SOURCES.txt'
    writing manifest file 'AxonDeepSeg.egg-info\SOURCES.txt'
    running build_ext
    Creating c:\users\stoyan\miniconda3\envs\ads_project2\lib\site-packages\AxonDeepSeg.egg-link (link to .)
    Adding AxonDeepSeg 3.2 to easy-install.pth file
    Installing axondeepseg-script.py script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    Installing axondeepseg.exe script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    Installing axondeepseg_test-script.py script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    Installing axondeepseg_test.exe script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    Installing download_models-script.py script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    Installing download_models.exe script to C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts
    
    Installed c:\users\stoyan\pycharmprojects\ads_project2\axondeepseg
    Trying URL: https://osf.io/2hcfv/?action=download&version=5
    Downloading: 100%|##########| 26.8M/26.8M [00:03<00:00, 8.39MB/s]
    Unzip...
    --> Folder created: C:\Users\Stoyan\PycharmProjects\ADS_project2\axondeepseg\default_TEM_model
    ERROR: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Stoyan\\AppData\\Local\\Temp\\tmp7p_081u5\\default_TEM_model.zip'
    ERROR: Data was not succesfully downloaded and unzipped- please check your link and filename and try again.
    Traceback (most recent call last):
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\shutil.py", line 566, in move
        os.rename(src, real_dst)
    FileNotFoundError: [WinError 2] The system cannot find the file specified: 'default_SEM_model' -> 'AxonDeepSeg\\models\\default_SEM_model'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\Scripts\download_models-script.py", line 33, in <module>
        sys.exit(load_entry_point('AxonDeepSeg', 'console_scripts', 'download_models')())
      File "c:\users\stoyan\pycharmprojects\ads_project2\axondeepseg\AxonDeepSeg\models\download_model.py", line 39, in main
        download_model()
      File "c:\users\stoyan\pycharmprojects\ads_project2\axondeepseg\AxonDeepSeg\models\download_model.py", line 34, in download_model
        shutil.move("default_SEM_model", str(sem_destination))
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\shutil.py", line 580, in move
        copy_function(src, real_dst)
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\shutil.py", line 266, in copy2
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'default_SEM_model'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Stoyan\PycharmProjects\ADS_project2\axondeepseg\setup.py", line 68, in <module>
        'develop': PostDevelopCommand,
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Stoyan\PycharmProjects\ADS_project2\axondeepseg\setup.py", line 28, in run
        check_call("download_models")
      File "C:\Users\Stoyan\Miniconda3\envs\ADS_project2\lib\subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'download_models' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Stoyan\Miniconda3\envs\ADS_project2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stoyan\\PycharmProjects\\ADS_project2\\axondeepseg\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sto
yan\\PycharmProjects\\ADS_project2\\axondeepseg\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full co
mmand output.

~~~

</details>

**Comment by Stoyan-I-A** [comment]
The error seems to happen in `ads_utils.download_data()`. I will try to debug this.

**Comment by Stoyan-I-A** [comment]
Creating a PR that fixes this
