### ISSUE TITLE
FSLeyes crashing

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/axondeepseg#544]
**Describe the bug**
When I first installed ADS a few months ago, I remember trying out `fsleyes` and installing the plugin. Everything worked fine from what I recall. I volunteered to write some doc for the plugin (#473) but now I can't open fsleyes anymore... I get the following error:
```bash
Traceback (most recent call last):
  File "/home/herman/.conda/envs/ads_venv/lib/python3.7/site-packages/fsl/utils/idle.py", line 576, in __idleLoop
    task.task(*task.args, **task.kwargs)
  File "/home/herman/.conda/envs/ads_venv/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 612, in create
    self.__createWXGLContext()
  File "/home/herman/.conda/envs/ads_venv/lib/python3.7/site-packages/fsleyes/gl/__init__.py", line 746, in __createWXGLContext
    self.__context = wxgl.GLContext(self.__canvas)
wx._core.wxAssertionError: C++ assertion ""tempContext"" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1616628589829/work/ext/wxWidgets/src/unix/glx11.cpp(498) in wxGLContext(): glXCreateContext failed
```

**To Reproduce**
```bash
$ conda activate ads_venv
$ fsleyes
```

**Platform (please complete the following information):**
 - OS: Manjaro 21.0.7 Ornara (kernel: x86_64 Linux 5.10.35-1-rt39-MANJARO)
 - AxonDeepSeg version number: 3.2.0 (master)

I am aware that there are issues installing fsleyes on Linux. I feel like I'm in a deadend right now because there doesn't seem to be a pre-release wxPython build for my distro and getting it up and running looks like a potential nightmare. I'll update this issue if I find anything useful.

**Comment by Stoyan-I-A** [comment]
Could you try the following:
- Create a new conda environment and activate it
- Download wxPython, perhaps not the most recent one. We could try this one: `conda install -c anaconda wxpython=4.0.1`
- Try to download FSLeyes conda install -c `conda-forge fsleyes=0.33.1`

**Comment by Stoyan-I-A** [comment]
If my last suggestion doesn't work, here's one last thing we could try:
- Create a new conda environment and activate it
- Install the most recent version of FSLeyes with this command: `conda install -c conda-forge fsleyes`

If that doesn't work, we might have to open an issue in the FSLeyes github project (https://github.com/pauldmccarthy/fsleyes).

**Comment by hermancollin** [comment]
Unfortunately I tried your suggestions but nothing has changed. If I can't get it to work tomorrow, I'll open an issue in the FSLeyes github project.

**Comment by Stoyan-I-A** [comment]
Do we have any update on this?

**Comment by hermancollin** [comment]
Sorry @Stoyan-I-A I haven't had the chance to investigate this further in the last weeks and it slipped my mind. Just opened an issue [here](https://github.com/pauldmccarthy/fsleyes/issues/81).

**Comment by hermancollin** [comment]
Here's a quick update:
For the past few days, the fsleyes maintainer has been trying to figure out what is causing my problem. I admire his efforts, but I am forced to ask the following question: _is fsleyes really the GUI option we want to maintain?_ I know there were efforts to find a more stable software for ADS integration.

I was told fsleyes is still somewhat widely used, so maybe it is still a good approach.
In defense of the fsleyes program, I admit my OS is definitely whimsical, making it hard to install these kinds of open-source projects and I'm considering dual booting another distro.

**Comment by Stoyan-I-A** [comment]
> is fsleyes really the GUI option we want to maintain?

Ideally, no. I would prefer something with more compatibility across operating systems.

FSLeyes was used because it was fairly simple to integrate ADS on it as a plugin.

**Comment by jcohenadad** [comment]
> _is fsleyes really the GUI option we want to maintain?_ I know there were efforts to find a more stable software for ADS integration.

nope! 😊   see: #404

> I was told fsleyes is still somewhat widely used, so maybe it is still a good approach.

it depends on the community. It is widely used by the MRI community and it is _absolutely not_ used by the microscopy community. As @Stoyan-I-A said in https://github.com/neuropoly/axondeepseg/issues/544#issuecomment-889929672 we used FSLeyes because we know it, but it is not a good enough reason to keep it if it is not a good long term solution.

**Comment by mathieuboudreau** [comment]
Stale - no longer supporting FSLeyes
